export const Gents={
    title:"Gents Fashion",
    image1: "Saved Pictures/Men/1.jpg",
    image2: "Saved Pictures/Men/7.jpg",
    image3: "Saved Pictures/Men/8.jpg",
    image4: "Saved Pictures/Men/9.jpg",
    image5: "Saved Pictures/Men/5.jpg",
    image6: "Saved Pictures/Men/6.jpg",
    price1:"559 INR",
    price2:"459 INR",
    price3:"659 INR",
    price4:"759 INR",
    price5:"859 INR", 
    price6:"959 INR",
}

export const Ladies={
    title:"Ladies Fashion",
    image1: "Saved Pictures/Women/10.jpg",
    image2: "Saved Pictures/Women/2.jpg",
    image3: "Saved Pictures/Women/3.jpg",
    image4: "Saved Pictures/Women/4.jpg",
    image5: "Saved Pictures/Women/11.jpg",
    image6: "Saved Pictures/Women/12.jpg",
    price1:"559 INR",
    price2:"459 INR",
    price3:"659 INR",
    price4:"759 INR",
    price5:"859 INR", 
    price6:"959 INR",
}